GraphQL naming conventions
commutatus/awesome pull request #115
Opened 2021-01-22 10:41 UTC by AdityaTiwari2102

2021-01-27 06:55 UTC, mikevic requested changes

2021-01-27 06:55 UTC, mikevic commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- Field names should use `camelCase`. Many GraphQL clients are written in JavaScript, Java, Kotlin, or Swift, all of which recommend camelCase for variable names.
@AdityaTiwari2102 - can you provide an example?

2021-01-27 06:55 UTC, mikevic commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- Type names should use `PascalCase`. This matches how classes are defined in the languages mentioned above.
@AdityaTiwari2102 - can you provide an example?

2021-01-27 06:55 UTC, mikevic commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- Enum values should use `ALL_CAPS`, because they are similar to constants.
@AdityaTiwari2102 - is there a way to easily translate the capital values to `kebab-case`, since we use kebab case in the projects.

2021-01-27 06:55 UTC, mikevic commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- File names include the name of the component the file represents. Plurals are used in folder names, but not in file names.
@AdityaTiwari2102 - can you provide an example

2021-01-27 06:55 UTC, mikevic commented
@AdityaTiwari2102 - I suggest moving all the changed related to the navigation to another PR and merging them. I guess you can cherry-pick the commits.

2021-01-27 14:19 UTC, AdityaTiwari2102 commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- File names include the name of the component the file represents. Plurals are used in folder names, but not in file names.
@mikevic - I have added the file and folder structure at the end, will that be enough?

2021-01-27 14:20 UTC, AdityaTiwari2102 commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- Enum values should use `ALL_CAPS`, because they are similar to constants.
@mikevic - Do you meant while sending the values?

2021-01-27 15:28 UTC, mikevic commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- Enum values should use `ALL_CAPS`, because they are similar to constants.
@AdityaTiwari2102 - yes. Cause we might want to use these enums directly in queries.

2021-01-27 15:28 UTC, mikevic commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- File names include the name of the component the file represents. Plurals are used in folder names, but not in file names.
@AdityaTiwari2102 @AdityaTiwari2102 - yes, it's okay. 

I want to also add another structure as an example, it's what we have in Ragya

queries/user/profile.rb
queries/user/list.rb

Here I put each query in it's own file. What do you think of this? I guess based on the size of the project it might change, for example I think AIESEC might benefit from this or some more segregation of the queries.

2021-01-28 07:04 UTC, AdityaTiwari2102 commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- File names include the name of the component the file represents. Plurals are used in folder names, but not in file names.
@mikevic - I got a mixed response with the approach. Some are of the opinion to keep the folder structure flat while others are favoring it as it will help and save time in searching rather than scrolling in the file because of which I haven't included it.

2021-01-28 07:08 UTC, AdityaTiwari2102 commented on domains/engineering/well-documented/graphql-naming-conventions.md
> +- Enum values should use `ALL_CAPS`, because they are similar to constants.
@mikevic - We can have a method that will convert the string into that format.
```ruby
def to_kebab
  return self.downcase.dasherize
end
```

2021-02-01 03:50 UTC, mikevic reviewed
Bro, I've added my feedback as comments.

2021-02-01 09:45 UTC, mikevic approved these changes

2021-02-10 14:02 UTC, merged