feat: razorpay integration doc
commutatus/awesome pull request #136
Opened 2021-09-29 19:37 UTC by jish0desarkar

2021-09-30 07:09 UTC, AdityaTiwari2102 requested changes
@jish0desarkar - It has a lot of formatting issues. Kindly check them as well.

2021-09-30 07:09 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +1. Create a method to process the order and pass the fetched\_order. Inside this method check if the status of the order is &#39;paid&#39; *(fetched\_order.status == &#39;paid&#39;)*, if so then go a
@jish0desarkar - Redundant line. Already mentioned above.

2021-09-30 07:09 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +post "/webhooks/process/:webhook_source",  controller::webhooks, action::process
@jish0desarkar -
```suggestion
post "/webhooks/process/:webhook_source",  controller: :webhooks, action: :process 
```

2021-09-30 07:09 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +		Razorpay::Utility.verify_webhook_signature(request.raw_post, request.headers["X-Razorpay-Signature"], Rails.application.credentials[Rails.env.to_sym][:razorpay_webhook_signature])
@jish0desarkar -
1. Ideally, each environment will have its own credentials file, right? If yes, we don't need to specify the environment while fetching them.
2. To access the hash it is best to use the dig.
```suggestion
		Razorpay::Utility.verify_webhook_signature(request.raw_post, request.headers["X-Razorpay-Signature"], Rails.application.credentials.dig(:razorpay_webhook_signature))
```

2021-10-11 10:27 UTC, jish0desarkar commented on domains/engineering/efficient/razorpay_integration.md
> +[![Razorpay admin panel](/assets/images/razorpay_admin_panel.gif)](/assets/images/razorpay_admin_panel.gif)
This gif is directly downloaded from Razorpay docs bro, This is not our platform

2021-10-11 10:27 UTC, jish0desarkar commented on domains/engineering/efficient/razorpay_integration.md
> +```
Regarding point 1, in Gehna we have only one credentials file were we keep all the creds indented under the environments, We don't have separate files

2021-12-13 04:51 UTC, AdityaTiwari2102 requested changes

2021-12-13 04:51 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +	Razorpay.setup(Rails.application.credentials.dig(Rails.env.to_sym, :razorpay_key_id),Rails.application.credentials.dig(Rails.env.to_sym,:razorpay_secret_token)
@jish0desarkar - Ideally we would have the different credential files for each environment.
```suggestion
	Razorpay.setup(Rails.application.credentials.dig(:razorpay_key_id), Rails.application.credentials.dig(:razorpay_secret_token))
```

2021-12-13 04:51 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +3. Create a file inside the ```config/initializers``` folder called **razorpay.rb**. Here require the razorpay library and set it up like so
@jish0desarkar
```suggestion
3. Create a file inside the `config/initializers` folder called **razorpay.rb**. Here require the razorpay library and set it up like so
```

2021-12-13 04:51 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +**Note:** Make sure to have only one method for creating an order or subscription which also will contain the verification of the payment. If ```the fetched_order``` status is **paid** then proceed.
@jish0desarkar 
```suggestion
**Note:** Make sure to have only one method for creating an order or subscription which also will contain the verification of the payment. If the `fetched_order` status is **paid** then proceed. This single method could be reused when webhooks will be implemented.
```

2021-12-13 04:51 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +				Razorpay::Utility.verify_webhook_signature(request.raw_post, request.headers["X-Razorpay-Signature"], Rails.application.credentials.dig(Rails.env.to_sym,:razorpay_webhook_signature)
@jish0desarkar - Ideally we would have the different credential files for each environment.
```suggestion
				Razorpay::Utility.verify_webhook_signature(request.raw_post, request.headers["X-Razorpay-Signature"], Rails.application.credentials.dig(:razorpay_webhook_signature))
```

2021-12-13 04:51 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +			cart.create_gehna_order(fetched_order)
@jish0desarkar - If I saw it right, we have renamed it to `create_platform_order`
```suggestion
			cart.create_platform_order(fetched_order)
```

2021-12-13 04:51 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +	razorpay_order_id = payload['payload']['order']['entity']['id']
@jish0desarkar - It would be better to access hash with `dig`. It would not break the code if any of the keys is nil.
```suggestion
	razorpay_order_id = payload.dig('payload', 'order', 'entity', 'id')
```

2021-12-13 04:51 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +		razorpay_order_id = payload["payload"]["order"]["entity"]["id"]
@jish0desarkar - Same here.
```suggestion
		razorpay_order_id = payload.dig('payload', 'order', 'entity', 'id')
```

2021-12-23 03:40 UTC, AdityaTiwari2102 requested changes

2021-12-23 03:40 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +		argument:cart_id, !types.String
@jish0desarkar -
```suggestion
		argument :cart_uuid, !types.String
```

2021-12-23 03:40 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +			cart = Cart.find_by(uuid:args[:cart_id])
@jish0desarkar -
```suggestion
			cart = Cart.find_by(uuid: args[:cart_uuid])
```

2021-12-23 03:40 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +		argument:cart_id, !types.String
@jish0desarkar -
```suggestion
		argument :cart_uuid, !types.String
```

2021-12-23 03:40 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +			cart = Cart.find_by(uuid:args[:cart_id])
@jish0desarkar -
```suggestion
			cart = Cart.find_by(uuid:args[:cart_uuid])
```

2021-12-23 03:40 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +		cart = Cart.find_by(razorpay_order_id:razorpay_order_id)
@jish0desarkar -
```suggestion
		cart = Cart.find_by(razorpay_order_id: razorpay_order_id) 
```

2021-12-23 03:40 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +### Note:
@jish0desarkar - Let's make it bold instead of heading else it would be added in TOC.
```suggestion
**Note:**
```

2022-01-10 12:49 UTC, AdityaTiwari2102 approved these changes

2022-01-10 12:49 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/razorpay_integration.md
> +	Razorpay.setup(Rails.application.credentials.dig(:razorpay_key_id),Rails.application.credentials.dig(Rails.env.to_sym,:razorpay_secret_token)
```suggestion
	Razorpay.setup(Rails.application.credentials.dig(:razorpay_key_id),Rails.application.credentials.dig(:razorpay_secret_token)
```

2022-01-10 12:50 UTC, merged

2022-02-01 13:17 UTC, anbublacky commented on domains/engineering/efficient/razorpay_integration.md
> +3. Generate a **WebhookEvent** model with the following table columns **source:integer**, **payload:json**, **event\_type:string**, **status:integer**, **webhook\_event\_id:string**.
Source should be string right