feat: slack documentation
commutatus/awesome pull request #137
Opened 2021-12-11 13:08 UTC by jish0desarkar

2022-01-10 12:27 UTC, mikevic commented
@AdityaTiwari2102 - bro, when you have time, please review this as well so we can move forward on this, thanks!

2022-01-11 14:09 UTC, AdityaTiwari2102 requested changes

2022-01-11 14:09 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/slack_integration.md
> +   2. For events we should provide a post request URL to slack, in which the slack will send a challenge parameter and in response we should provide the challenge value. IF the URL isn&#39;t able to
@jish0desarkar -
```suggestion
   1. Events are basically any event occurring on a slack app like clicking a home tab, adding a user to the team, a user making changes to his details, etc.,
   2. For events we should provide a post request URL to slack, in which the slack will send a challenge parameter and in response, we should provide the challenge value. IF the URL isn&#39;t able to respond with the challenge parameter, URL won&#39;t get approved by slack.
```

2022-01-11 14:09 UTC, AdityaTiwari2102 commented on domains/engineering/efficient/slack_integration.md
> +9. We also have to add this app to the channel where we want to post the messages otherwise when we&#39;ll try to send the message, the Slack Client in the code will throw error.
@jish0desarkar -
```suggestion
9. We also have to add this app to the channel where we want to post the messages otherwise when we&#39;ll try to send the message, the Slack Client in the code will throw an error.
```

2022-01-13 18:36 UTC, merged